# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ea7d669014bc192a3d3587fe2baa34a2"
name = "Phoenix Flow"
application_url = "https://ironphoenixflow.com"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_files,read_inventory,read_legal_policies,read_merchant_managed_fulfillment_orders,read_orders,read_products,read_shipping,read_themes,write_content,write_files,write_inventory,write_products,write_themes"

[auth]
redirect_urls = [
  "https://ironphoenixflow.com/auth/callback",
  "https://ironphoenixflow.com/auth/shopify/callback",
  "https://ironphoenixflow.com/api/auth/callback"
]
